### ISSUE TITLE
Docker builds failing

### ISSUE THREAD

**Issue by rubenv** [clue/docker-ttrss#27] opened 2016-07-27 12:40 UTC
Looks like the Docker Hub builds have stopped working:

> Build failed: The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y nginx supervisor php5-fpm php5-cli php5-curl php5-gd php5-json php5-pgsql php5-mysql php5-mcrypt && apt-get clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

I'm guessing this is due to the use of `FROM ubuntu` (without a version specified), with a recent Ubuntu upgrade dropping PHP5.

**Comment by clue** [comment] 2016-07-27 12:52
Thanks for reporting this!

Do you feel like filing PR to fix this? :+1:

**Comment by rubenv** [comment] 2016-07-27 12:58
@clue was already prepping one, #28 should fix things.

**Comment by clue** [comment] 2016-07-27 13:49
Running this yields the following log results, unfortunately:

```
…
2016-07-27 13:47:52,918 INFO spawned: 'ttrss-update-daemon' with pid 22
2016-07-27 13:47:53,007 INFO exited: ttrss-update-daemon (exit status 255; not expected)
2016-07-27 13:47:54,008 INFO gave up: ttrss-update-daemon entered FATAL state, too many start retries too quickly
```

**Comment by rubenv** [comment] 2016-07-27 13:52
Right, a quick Google tells me that TTRSS might not even work on PHP 7 yet.

Easier solution will then probably be pinning the Dockerfile to some older Ubuntu release (that ships PHP5).

**Comment by clue** [comment] 2016-07-27 16:35
I haven't confirmed this, but it looks like TTRSS ought to run PHP 7?

Either way, both solutions will be fine for now. Care to file a new PR and close this one if you downgrade Ubuntu to a specific release?

**Comment by rubenv** [comment] 2016-07-28 08:15
@clue I've pinned it to Ubuntu Wily for now. That should fix things right now.

I'd recommend converting this image to Alpine at some point though, it'll make it much smaller.

**Comment by clue** [comment] 2016-07-28 10:57
> I'd recommend converting this image to Alpine at some point though, it'll make it much smaller.

I'm not opposed to switching to a smaller base image, PRs are much appreciated :+1:

**Comment by rubenv** [comment] 2016-07-28 12:11
Submitted two more pull requests:
- #30 Switches to Alpine, image size: 100.2 MB
- #31 Switches to Alpine + s6, image size: 59.97 MB

By comparison, the Ubuntu based image is 278.3 MB

**Closed as completed** 2023-07-03 07:19 UTC
Labels: bug, help wanted, easy pick
